name = "links"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-01-01"
routes = [
  { pattern = "src.rip", custom_domain = true }
]

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"
not_found_handling = "single-page-application"

[observability.logs]
enabled = true
